@startuml
class UsEuCarAdapter {
- CarUSInterface car

}
interface CarUSInterface {
~ double getTopSpeedInMph()
}
interface EuCarAdapterInterface {
+ double getTopSpeed()
+ double getLength()
}
class FordMustang {
+ double getTopSpeedInMph()
+ double getTopSpeedInMph()
}


EuCarAdapterInterface <|.. UsEuCarAdapter
CarUSInterface <|.. FordMustang
@enduml