@startuml
class UsEuCarAdapter {
- CarUSInterface car

}
interface CarUSInterface {
+ double getTopSpeedInMph()
+ double getLengthInMiles()
}

interface EuCarAdapterInterface {
+ double getTopSpeedInKph()
+ double getLengthInMeter()
}

class FordMustang {

}


EuCarAdapterInterface <|.. UsEuCarAdapter
CarUSInterface <|.. FordMustang
@enduml